version: "3.5"

services:
  obp_institution_db:
    image: openbookpublishers/obp_institution_db:latest
    container_name: "obp_institution_db"
    restart: unless-stopped
    volumes:
      - institutiondb:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - db.env

volumes:
  institutiondb:
